### ISSUE TITLE
cannot run in windows X + electron

### ISSUE THREAD

**Issue by vsix27** [ronomon/utimes#1]
it runs on Mac (almost always, rarely it does not change times, but usually does), but cannot install/use package in windows X (vm)
after running 'npm install @ronomon/utimes --safe', installing asked python, 'npm install'
when trying to use the code, it gives : 
ELECTRON_ASAR.js:166 Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\...\node_modules\@ronomon\utimes\binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\...\node_modules\@ronomon\utimes\index.js:11:15)
    at Object.<anonymous> (C:\...\node_modules\@ronomon\utimes\index.js:118:3)

**Comment by jorangreef** [comment]
Please see: https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md
